
"""
Django settings for todoApp project.
Generated by 'django-admin startproject' using Django 2.2.7.
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = '8)810zj@#^2xp=1=2rkozbv8#)gub6m1a^9qf&)d-9&x9*c2a_'

DEBUG = True

# ✅  FIXED
ALLOWED_HOSTS = ['*']
# OR:
# ALLOWED_HOSTS = ['13.59.158.153']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'todoApp',
    'todos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
                                                                                                                                     1,3           Top
